const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { JSDOM, VirtualConsole } = require('jsdom');
const directory = fs.mkdtempSync(path.join(os.tmpdir(),'meditrack-ui-'));
process.env.DB_PATH = path.join(directory,'ui.db');
process.env.SESSION_DIR = directory;
process.env.SESSION_SECRET = 'isolated-ui-tests-secret';
process.env.NODE_ENV = 'test';
require('../database/seed')();
const {app,store}=require('../server');
const db=require('../database/database');
let server, dom;
async function until(check) { const deadline=Date.now()+8000; while(Date.now()<deadline){if(check())return; await new Promise(r=>setTimeout(r,25));} throw new Error('No se cumplió la condición de interfaz'); }
test('frontend original: login, navegación, filtros, formularios CRUD, modal y logout',async()=>{
  server=app.listen(0);
  await new Promise(r=>server.once('listening',r));
  const errors=[];
  const virtualConsole=new VirtualConsole(); virtualConsole.on('jsdomError',e=>errors.push(e.message));
  dom=await JSDOM.fromURL('http://127.0.0.1:'+server.address().port,{resources:'usable',runScripts:'dangerously',virtualConsole,beforeParse(window){window.scrollTo=()=>{};window.confirm=()=>true;}});
  await until(()=>dom.window.jQuery && dom.window.jQuery('#loginAlert').text().length);
  const $=dom.window.jQuery;
  const fill=(id,values)=>{for(const [name,value] of Object.entries(values)) $(`#${id} [name="${name}"]`).val(value);};
  const assertLoggedOut = () => {
    assert.equal($('#mainNav').css('display'),'none');
    assert.equal($('#logoutButton').css('display'),'none');
    assert.equal($('.view.active').attr('id'),'view-login');
    assert.ok($('.view:not(#view-login)').toArray().every(view=>view.hidden));
    assert.equal($('.app-shell').css('grid-template-columns'),'minmax(0, 1fr)');
  };
  assertLoggedOut();
  const initial = new JSDOM(fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8'));
  const style = initial.window.document.createElement('style');
  style.textContent = fs.readFileSync(path.join(__dirname,'../public/css/styles.css'),'utf8');
  initial.window.document.head.append(style);
  assert.equal(initial.window.getComputedStyle(initial.window.document.querySelector('#mainNav')).display,'none');
  initial.window.close();
  fill('loginForm',{email:'admin@meditrack.test',password:'Admin123*'}); $('#loginForm').trigger('submit');
  await until(()=>$('#view-dashboard').hasClass('active'));
  assert.match($('#userChip').text(),/Administrador/);
  assert.notEqual($('#mainNav').css('display'),'none');
  assert.equal($('[data-view="administracion"]').prop('hidden'),false);
  const restored = await JSDOM.fromURL('http://127.0.0.1:'+server.address().port,{cookieJar:dom.cookieJar,resources:'usable',runScripts:'dangerously',virtualConsole,beforeParse(window){window.scrollTo=()=>{};}});
  try {
    await until(()=>restored.window.jQuery?.('#view-dashboard').hasClass('active'));
    assert.notEqual(restored.window.jQuery('#mainNav').css('display'),'none');
  } finally { restored.window.close(); }
  assert.equal($('#patientsTableBody tr').length,5);
  $('[data-view="pacientes"]').trigger('click');
  $('#patientSearch').val('Ana').trigger('input'); assert.equal($('#patientsTableBody tr').length,1);
  $('#patientSearch').val('').trigger('input');
  $('[data-action="open-patient-form"]').first().trigger('click');
  fill('patientForm',{nombre:'UI & <b>Paciente</b>',apellido:'Ensayo',identificacion:'UI-123',fecha_nacimiento:'2000-01-01',sangre:'A+',telefono:'6000-1234',correo:'ui@example.test',estado:'ACTIVO'});
  $('#patientForm').trigger('submit');
  await until(()=>$('#patientsTableBody tr').length===6);
  assert.match($('#patientsTableBody').text(),/UI & Paciente/);
  assert.equal($('#patientsTableBody script').length,0);
  $('#patientsTableBody .edit-record').last().trigger('click');
  await until(()=>$('#patientForm').data('editId'));
  assert.equal($('#patientName').val(),'UI & Paciente');
  $('#patientName').val('Paciente Editado'); $('#patientForm').trigger('submit');
  await until(()=>$('#patientsTableBody').text().includes('Paciente Editado'));
  $('#patientsTableBody .view-patient').last().trigger('click'); assert.match($('#recordTitle').text(),/Paciente Editado/);
  $('[data-view="personal"]').trigger('click');
  fill('doctorForm',{nombre:'Dra. UI',especialidad:'General',registro:'UI-MED',turno:'08:00–16:00',estado:'DISPONIBLE'});
  $('#doctorForm').trigger('submit'); await until(()=>$('#doctorsTableBody tr').length===6);
  $('#doctorsTableBody .edit-record').last().trigger('click'); await until(()=>$('#doctorForm').data('editId'));
  $('#doctorName').val('Dra. UI Editada'); $('#doctorForm').trigger('submit'); await until(()=>$('#doctorsTableBody').text().includes('Dra. UI Editada'));
  $('[data-view="citas"]').trigger('click');
  $('#appointmentPatient').val($('#appointmentPatient option').last().val());
  $('#appointmentSpecialty').val('General').trigger('change');
  fill('appointmentForm',{fecha:'2026-12-01',hora:'14:00'});
  $('#appointmentForm').trigger('submit'); await until(()=>$('#appointmentList .appointment-item').length===5);
  $('#appointmentList .edit-record').last().trigger('click'); await until(()=>$('#appointmentForm').data('editId'));
  assert.equal($('#appointmentSpecialty').val(),'General'); assert.ok($('#appointmentDoctor').val());
  $('#appointmentTime').val('14:30'); $('#appointmentForm').trigger('submit'); await until(()=>$('#appointmentList').text().includes('14:30'));
  $('#appointmentList .appointment-info').last().trigger('click'); assert.equal($('#infoModal').hasClass('hidden'),false);
  $(dom.window.document).trigger($.Event('keydown',{key:'Escape'})); assert.equal($('#infoModal').hasClass('hidden'),true);
  $('#toggleAgendaMode').trigger('click'); assert.match($('#agendaTitle').text(),/compacta/);
  $('#appointmentList .delete-record').last().trigger('click'); await until(()=>$('#appointmentList .appointment-item').length===4);
  $('#doctorsTableBody .delete-record').last().trigger('click'); await until(()=>$('#doctorsTableBody tr').length===5);
  $('#patientsTableBody .delete-record').last().trigger('click'); await until(()=>$('#patientsTableBody tr').length===5);
  $('[data-view="administracion"]').trigger('click'); assert.equal($('#usersTableBody tr').length,3);
  $('#logoutButton').trigger('click'); await until(()=>$('#view-login').hasClass('active'));
  assert.equal($('#patientsTableBody tr').length,0);
  assertLoggedOut();
  $('[data-view="pacientes"]').trigger('click'); assert.equal($('#view-login').hasClass('active'),true);
  for (const [email,password] of [['recepcion@meditrack.test','Recepcion123*'],['medico@meditrack.test','Medico123*']]) {
    fill('loginForm',{email,password}); $('#loginForm').trigger('submit');
    await until(()=>$('#view-dashboard').hasClass('active'));
    assert.notEqual($('#mainNav').css('display'),'none');
    assert.equal($('[data-view="administracion"]').css('display'),'none');
    assert.equal($('#view-administracion').prop('hidden'),true);
    $('[data-view="administracion"]').trigger('click');
    assert.equal($('#view-dashboard').hasClass('active'),true);
    $('#logoutButton').trigger('click'); await until(()=>$('#view-login').hasClass('active'));
    assertLoggedOut();
  }
  assert.deepEqual(errors,[]);
});
after(async()=>{dom?.window.close(); if(server)await new Promise(r=>server.close(r));await new Promise(r=>store.db.close(r)); db.close();fs.rmSync(directory,{recursive:true,force:true});});
