PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL,
 email TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL,
 rol TEXT NOT NULL CHECK(rol IN ('Administrador','Recepción','Médico')),
 area TEXT NOT NULL, estado TEXT NOT NULL CHECK(estado IN ('ACTIVO','INACTIVO')),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS patients (
 id INTEGER PRIMARY KEY AUTOINCREMENT, expediente TEXT NOT NULL UNIQUE,
 nombre TEXT NOT NULL, apellido TEXT NOT NULL, identificacion TEXT NOT NULL UNIQUE,
 fecha_nacimiento TEXT NOT NULL, sangre TEXT NOT NULL, telefono TEXT NOT NULL DEFAULT '',
 correo TEXT NOT NULL DEFAULT '', estado TEXT NOT NULL CHECK(estado IN ('ACTIVO','SEGUIMIENTO','CONTROL')),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS patient_followups (
 id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 fecha TEXT NOT NULL, descripcion TEXT NOT NULL, estado TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_followups_patient ON patient_followups(patient_id, fecha);
CREATE INDEX IF NOT EXISTS idx_patients_name ON patients(nombre, apellido);
CREATE TABLE IF NOT EXISTS doctors (
 id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL, especialidad TEXT NOT NULL,
 registro TEXT NOT NULL UNIQUE COLLATE NOCASE, turno TEXT NOT NULL,
 estado TEXT NOT NULL CHECK(estado IN ('DISPONIBLE','EN CONSULTA','PRÓXIMO TURNO')),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS appointments (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE RESTRICT,
 doctor_id INTEGER NOT NULL REFERENCES doctors(id) ON DELETE RESTRICT,
 especialidad TEXT NOT NULL, fecha TEXT NOT NULL, hora TEXT NOT NULL,
 estado TEXT NOT NULL CHECK(estado IN ('PROGRAMADA','CONFIRMADA','EN ESPERA','FINALIZADA','CANCELADA')),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_doctor_slot ON appointments(doctor_id, fecha, hora) WHERE estado <> 'CANCELADA';
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments(fecha, hora);
